### ISSUE TITLE
Stocks not found

### ISSUE THREAD

**Issue by peter149** [damianboh/get_fundamental_ratios#1]
Hi, I'm not a programmer and  try your code. But stocks are "not found". So the data of stocks are also not found. How to correct. Thanks

**Comment by cgestraviz** [comment]
You can see a solution here:
[https://medium.com/@dan.kenan/the-data-are-available-but-it-seems-that-finviz-is-using-bot-detection-ae95db530388](url)

**Comment by damianboh** [comment]
The code has been changed accordingly to address that. Thank you for pointing that out!
